script_key="deYEKZHqqochjWOOYEJIeiLfAUeqPGio";
getgenv().Settings = {
    Sniper = {
        Active = true,
        Items = {
            SearchTerminal = {
                
                ["2024 Gargantuan Christmas Present"] = {Price = 15000000},
                ["Exclusive Egg 40"] = {Price = 40000000},
                ["2025 New Years Gift"] = {Price = 10000000},
                ["Jolly Gift"] = {Price = "50%"},
                ["Candycane"] = {Price = 1500},
                ["Christmas Cookie"] = {Price = 5500},
                ["Hot Cocoa"] = {Price = 6000},
                ["Snowflake Gift"] = {Price = 10000},
                ["Rainbow Mini Chest"] = {Price = 600000},
                ["Mini Pinata"] = {Price = 13000},
                ["Secret Key"] = {Price = 17500},
                ["Void Key"] = {Price = 45000},
                ["Mini Chest"] = {Price = 30000},
                ["Crystal Key"] = {Price = 10000},
                ["Magic Shard"] = {Price = "40%"},
                ["Tech Key"] = {Price = 13500},
                ["Golden Prison Key"] = {Price = 140000},
                ["Spinny Wheel Ticket"] = {Price = "85%"},
                ["Tech Spinny Wheel Ticket"] = {Price = "50%"},
                ["Void Spinny Wheel Ticket"] = {Price = "50%"},
                ["Overload"] = {Price = "30%"},
                ["Royalty"] = {Price = "25%"},
                ["Exotic Treasure Flag"] = {Price = "50%"},
                ["The Cocktail"] = {Price = "40%"},
                ["Mastery"] = {Price = "25%"},
                ["Coins VII"] = {Price = "1%"},
                ["Glitched Drive"] = {Price = "35%"},
                ["Super Magnet"] = {Price = "25%"},
                ["Rainbow Eggs"] = {Price = "25%"},
                ["Crystal Key Upper Half"] = {Price = "+50%"},
                ["Void Key Upper Half"] = {Price = "+50%"},
                ["Tech Key Upper Half"] = {Price = "+50%"},
                ["Secret Key Upper Half"] = {Price = "+50%"},
                ["Chest Mimic"] = {Price = "25%"},
                ["Hidden Treasure"] = {Price = "25%"},
                ["Black Hole"] = {Price = "30%"},
                ["Shiny Apple"] = {Price = 33},
                ["Shiny Banana"] = {Price = 100},
                ["Shiny Pineapple"] = {Price = 33},
                ["Shiny Orange"] = {Price = 75},
                ["Shiny Watermelon"] = {Price = 100},

            },

            ["All Huges"] = {Price = "95%", DetectManipulation = true, AllTypes = true},
            ["Rainbow All Huges"] = {Price = 35000000},
            ["Golden All Huges"] = {Price = 13000000},
            ["Shiny All Huges"] = {Price = 45000000},
            ["All Class: Misc"] = {Price = 5},
            ["All Class: Fruit"] = {Price = 3},
            ["All Class: Enchant"] = {Price = 5},
            ["All Class: Potion"] = {Price = 5},
            ["All Class: Egg"] = {Price = "50%", DetectManipulation = true},
            ["All Exclusives"] = {Price = 750000},
            
        },
        ["Switch Servers"] = {Active = false, SecondDelay = 7, OnlyPRO = false},
        ["Webhook"] = {Active = true, URL = "https://discord.com/api/webhooks/1318927648814010429/66CdX1sWT551GUnyOeUyDnEujQX7YpG4L1IdhjIl14GiFzxxAtA2mdBrFURh95ruRGS-"},
        ["Kill Switch"] = {
            ["Limits Reached"] = false,
            ["Diamonds Hit: 5000000"] = true,
            ["60 Minutes Timer"] = false,
            ["^^^ Switch To Selling"] = true,
        },
    },

    Seller = {
        Active = true,
        Items = {
            ["Crystal Key"] = {Price = 12500},
            ["Secret Key"] = {Price = 20000},
            ["Void Key"] = {Price = 50000},
            ["Tech Key"] = {Price = 18000},
            ["Mini Chest"] = {Price = 32500},
            ["Mini Pinata"] = {Price = 20000},
            ["Golden Prison Key"] = {Price = 155000},
            ["Rainbow Mini Chest"] = {Price = 650000},
             
        },
        ["Switch Servers"] = {Active = true, MinuteDelay = 20, OnlyPRO = false},
        ["Webhook"] = {Active = true, URL = "https://discord.com/api/webhooks/1260057028492263534/1Hv58CzGgOr55p53sYyGjp_kmbZLkAjvDNNflFS4Rwl3ERt8_hcpErru88NktYcI0ITo"},
        ["Kill Switch"] = {
            ["Booth Runout"] = true,
            ["Diamonds Hit: 1b"] = false,
            ["60 Minutes Timer"] = false,
            ["^^^ Switch To Sniping"] = true,
        },
        ["Diamonds Sendout"] = {Active = false, Username = "", Amount = "1b"},
    },

    [[ Thank you for using System Exodus <3! ]]
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/3b58d9c50c5ea74f255af40a8f735773.lua"))()
